// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlpppOuq92oVafrzT-y-6gB5ExvLSD9Y',
    appId: '1:709155097090:web:6f5904aa0ba179a5b3b51b',
    messagingSenderId: '709155097090',
    projectId: 'faceticket-27f12',
    authDomain: 'faceticket-27f12.firebaseapp.com',
    storageBucket: 'faceticket-27f12.appspot.com',
    measurementId: 'G-XQPSDY9NK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKtTObKCZkJ8WcWVVN7_WOSxA_XcqU690',
    appId: '1:709155097090:android:632e2f5dd069e97fb3b51b',
    messagingSenderId: '709155097090',
    projectId: 'faceticket-27f12',
    storageBucket: 'faceticket-27f12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwinswCzIuvQnpbKjvb_wPE7klZhPqz3E',
    appId: '1:709155097090:ios:19bd48ae22bd205bb3b51b',
    messagingSenderId: '709155097090',
    projectId: 'faceticket-27f12',
    storageBucket: 'faceticket-27f12.appspot.com',
    iosClientId: '709155097090-3ipklh0193arf6s0k9gpmcpfpg11t5o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwinswCzIuvQnpbKjvb_wPE7klZhPqz3E',
    appId: '1:709155097090:ios:dbae7ad57869e321b3b51b',
    messagingSenderId: '709155097090',
    projectId: 'faceticket-27f12',
    storageBucket: 'faceticket-27f12.appspot.com',
    iosClientId: '709155097090-e0m6dm0morfqqbjvibk4roon6a9ebhve.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
